### PR TITLE
Replaced media_* for static_*

### PR DESCRIPTION
**Pull request by danodonovan**
According to the django devs as per version 1.3, static files should be held in STATIC_ROOT not MEDIA_ROOT - as 101 other pull requests I've changed this over. Seems to work ok.

### CODE REVIEW

**Comment by shreddd** [comment]
Could the authors of Django Compress comment on this issue? It seems like using STATIC_ROOT is the right thing to do, especially with the latest updates to static file management in Django (https://docs.djangoproject.com/en/dev/howto/static-files/) Would it be possible to merge this pull request, or implement something similar in django-compress?

**Comment by danodonovan** [comment]
I'd also advocate going for the pull https://github.com/pelme/django-compress if you can stomach setting a COMPRESS_\* (which could help with backward compatibility). That pull has some other tasty bug fixes too.

**Comment by cyberdelia** [comment]
This project is mostly abandoned by the original author. See #3

**Comment by pelme** [comment]
As you might have noticed, django-compress has not been updated in a long time.

I will not continue to maintain it in the future, I suggest you check out cyberdelias django-pipeline fork instead!

Sorry for the inconvenience!

**Comment by shreddd** [comment]
Thanks. I will look into django-pipeline. We appreciate all the initial work done with django-compress. It has worked really well for us so far.

**Pull request closed without merging**
